### ISSUE TITLE
After sharing quote by email, opacity stays when tbAlert dismissed

### ISSUE THREAD

**Issue by stevedowney** [stevedowney/smds#25]

**Comment by stevedowney** [comment]
If this isn't a quick fix push to next milestone

**Comment by marcodicostanzo** [comment]
I think my comment didn't work to close the ticket, but it should be fixed in b944dae..72332d1  master -> master

Steve, can you tell me where the div.modal-backdrop is being created? My search for it only turned up the CSS rule for it. That element should have an ID associated with it to optimize jQuery's speed when looking for it in the DOM.
